//basic
export const SET_FORCED_SONG_ON_MUSIC_PLAYER =
  "SET_FORCED_SONG_ON_MUSIC_PLAYER";

//internet
export const SET_USER_LOCATION_INFO = "SET_USER_LOCATION_INFO";

export const SET_USER_WEATHER_INFO = "SET_USER_WEATHER_INFO";

export const SET_SERIOUS_NEWS = "SET_SERIOUS_NEWS";

export const SET_SILLY_NEWS = "SET_SILLY_NEWS";

export const SET_QUOTE = "SET_QUOTE";

export const SET_RANDOM_COMIC = "SET_RANDOM_COMIC";

export const SET_LOADING_COMIC = "SET_LOADING_COMIC";
