//basic
export const SET_FORCED_SONG_ON_MUSIC_PLAYER =
  "SET_FORCED_SONG_ON_MUSIC_PLAYER";

//internet
export const SET_USER_LOCATION_INFO = "SET_USER_LOCATION_INFO";

export const SET_USER_WEATHER_INFO = "SET_USER_WEATHER_INFO";
