//basic
export const SET_FORCED_SONG_ON_MUSIC_PLAYER =
  "SET_FORCED_SONG_ON_MUSIC_PLAYER";

export const OPEN_SIGN_IN = "OPEN_SIGN_IN";

export const CLOSE_SIGN_IN = "CLOSE_SIGN_IN";

export const OPEN_SIGN_UP = "OPEN_SIGN_UP";

export const CLOSE_SIGN_UP = "CLOSE_SIGN_UP";

//internet
export const INCREMENT_MASSIVE_REQUESTS_COUNT =
  "INCREMENT_MASSIVE_REQUESTS_COUNT";

export const SET_USER_LOCATION_INFO = "SET_USER_LOCATION_INFO";

export const SET_USER_WEATHER_INFO = "SET_USER_WEATHER_INFO";

export const SET_SERIOUS_NEWS = "SET_SERIOUS_NEWS";

export const SET_SILLY_NEWS = "SET_SILLY_NEWS";

export const SET_QUOTE = "SET_QUOTE";

export const SET_RANDOM_COMIC = "SET_RANDOM_COMIC";

export const SET_LOADING_COMIC = "SET_LOADING_COMIC";

export const SET_LATEST_NEWS = "SET_LATEST_NEWS";

export const SET_MYCOUNTRY_NEWS = "SET_MYCOUNTRY_NEWS";

//authentication
export const AUTHENTICATION_START = "AUTHENTICATION_START";

export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";

export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";

//save and fetch
export const SAVE_ITEM_START = "SAVE_ITEM_START";

export const SAVE_ITEM_SUCCESS = "SAVE_ITEM_SUCCESS";

export const SAVE_ITEM_FAIL = "SAVE_ITEM_FAIL";

export const FETCH_ITEMS_START = "FETCH_ITEMS_START";

export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";

export const FETCH_ITEMS_FAIL = "FETCH_ITEMS_FAIL";

export const DELETE_ITEM_START = "DELETE_ITEM_START";

export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";

export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
